export enum ErrorKind {
  CLIENT = 'CLIENT',
  DEPENDENCY = 'DEPENDENCY',
  INTERNAL = 'INTERNAL',
}

export enum ErrorCode {
  // common
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMITED = 'RATE_LIMITED',
  DEPENDENCY_UNAVAILABLE = 'DEPENDENCY_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  CLIENT_ERROR = 'CLIENT_ERROR',
  // auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REUSE = 'AUTH_TOKEN_REUSE',
  AUTH_RESET_CODE_INVALID = 'AUTH_RESET_CODE_INVALID',
  AUTH_SERVICE_CREDENTIAL_INVALID = 'AUTH_SERVICE_CREDENTIAL_INVALID',
  // user
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  // file
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_INVALID_STATE = 'FILE_INVALID_STATE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_MIME_NOT_ALLOWED = 'FILE_MIME_NOT_ALLOWED',
  FILE_UPLOAD_MISSING = 'FILE_UPLOAD_MISSING',
  // shared (tags, comments, attachments, activity)
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',
  TAG_EXISTS = 'TAG_EXISTS',
  TAG_IMMUTABLE = 'TAG_IMMUTABLE',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_EXISTS = 'ATTACHMENT_EXISTS',
  // search
  SEARCH_COLLECTION_NOT_FOUND = 'SEARCH_COLLECTION_NOT_FOUND',
  SEARCH_COLLECTION_EXISTS = 'SEARCH_COLLECTION_EXISTS',
  SEARCH_QUERY_INVALID = 'SEARCH_QUERY_INVALID',
  SEARCH_RECORD_NOT_FOUND = 'SEARCH_RECORD_NOT_FOUND',
  SEARCH_UNAVAILABLE = 'SEARCH_UNAVAILABLE',
  // config / crypto
  CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND',
  MAIL_CONFIG_MISSING = 'MAIL_CONFIG_MISSING',
  CRYPTO_DECRYPT_FAILED = 'CRYPTO_DECRYPT_FAILED',
  CRYPTO_MISCONFIGURED = 'CRYPTO_MISCONFIGURED',
  SETTING_VERSION_CONFLICT = 'SETTING_VERSION_CONFLICT',
  FEATURE_FLAG_NOT_FOUND = 'FEATURE_FLAG_NOT_FOUND',
  RETENTION_POLICY_NOT_FOUND = 'RETENTION_POLICY_NOT_FOUND',
  // calendar / scheduling
  CALENDAR_EVENT_NOT_FOUND = 'CALENDAR_EVENT_NOT_FOUND',
  CALENDAR_OCCURRENCE_NOT_FOUND = 'CALENDAR_OCCURRENCE_NOT_FOUND',
  CALENDAR_RULE_INVALID = 'CALENDAR_RULE_INVALID',
  SCHEDULED_JOB_NOT_FOUND = 'SCHEDULED_JOB_NOT_FOUND',
  SCHEDULER_HANDLER_NOT_REGISTERED = 'SCHEDULER_HANDLER_NOT_REGISTERED',
  // mailbox
  MAILBOX_MESSAGE_NOT_FOUND = 'MAILBOX_MESSAGE_NOT_FOUND',
  MAILBOX_ATTACHMENT_NOT_FOUND = 'MAILBOX_ATTACHMENT_NOT_FOUND',
  MAILBOX_ACCOUNT_UNRESOLVED = 'MAILBOX_ACCOUNT_UNRESOLVED',
  MAILBOX_SYNC_FAILED = 'MAILBOX_SYNC_FAILED',
  // agent / llm
  AGENT_CONVERSATION_NOT_FOUND = 'AGENT_CONVERSATION_NOT_FOUND',
  AGENT_APPROVAL_NOT_FOUND = 'AGENT_APPROVAL_NOT_FOUND',
  AGENT_APPROVAL_CONFLICT = 'AGENT_APPROVAL_CONFLICT',
  AGENT_APPROVAL_FORBIDDEN = 'AGENT_APPROVAL_FORBIDDEN',
  AGENT_REQUEST_INVALID = 'AGENT_REQUEST_INVALID',
  AGENT_RUN_FAILED = 'AGENT_RUN_FAILED',
  TOOL_EXECUTION_FAILED = 'TOOL_EXECUTION_FAILED',
  LLM_RATE_LIMITED = 'LLM_RATE_LIMITED',
  LLM_TIMEOUT = 'LLM_TIMEOUT',
  LLM_PROVIDER_ERROR = 'LLM_PROVIDER_ERROR',
  // infra
  DB_UNAVAILABLE = 'DB_UNAVAILABLE',
  CACHE_UNAVAILABLE = 'CACHE_UNAVAILABLE',
  QUEUE_UNAVAILABLE = 'QUEUE_UNAVAILABLE',
  STORAGE_UNAVAILABLE = 'STORAGE_UNAVAILABLE',
  STORAGE_OBJECT_NOT_FOUND = 'STORAGE_OBJECT_NOT_FOUND',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
}
